version: "3.9"
services:
  backend:
    image: 488940122412.dkr.ecr.eu-central-1.amazonaws.com/eficode:backend
    ports:
      - "9000:9000"
    environment:
      - APPID=${APPID}
  frontend:
    image: 488940122412.dkr.ecr.eu-central-1.amazonaws.com/eficode:frontend
    environment:
      - ENDPOINT=${ENDPOINT}
    ports:
      - "8000:8000"